# Cipher Configuration
# ---
# If changed, project WILL STOP working, there is NO WAY AROUND if keys are lost or changed!
# Do NOT change these keys at ANY POINT AFTER INITIALISATION OF PROJECT! DO NOT!

# Primary Cipher Key
primary: "PRIMARY enter some random words or PRNG entropy here"
# Secondary Key
secondary: "SEC enter some random words or PRNG entropy here"
# Users models encryption
users: "OOSERS enter some random words or PRNG entropy here"
# Project models encryption
project: "PRAJACKET enter some random words or PRNG entropy here"
# Misc encryption
misc: "MISCELANIEOUS enter some random words or PRNG entropy here"
